### ISSUE TITLE
gemv! test

### ISSUE THREAD

**Issue by sw2030** [ranjanan/DIA.jl#5]
`gemv!(tA, alpha, A, b, beta, ret)` is currently returning probably `alpha * A * beta * b + ret`

where we need `alpha*A*b + beta*ret`

**Comment by sw2030** [comment]
line 104 - `@assert S.n == length(b)` should be `@assert A.n == length(b)`
also `d = A.diags` for line 105

**Comment by ranjanan** [comment]
Fixed by 24fa0835d878063b61275092100cf730f45a2541
